Algoritmo "exercicioAula9"
Var

contar, comeco, final: inteiro


Inicio

Escreval(">>>Contar<<< ")

Escreval(" Inicio:")
Leia(comeco)

Escreval("Final:")
Leia(final)

Escreval (">>> a contagem é")

contar <- comeco

Enquanto ( contar <= final) faca

 Escreval(contar)

 contar <- contar + 1

 FimEnquanto
 
Enquanto (contar >= final)faca

Escreval(contar)

 contar <- contar - 1

 FimEnquanto


Fimalgoritmo