Algoritmo "matriz"

Var

matri:vetor[1..3, 1..2] de inteiro
linha, coluna: inteiro

Inicio

      para linha <- 1 ate 3 faca
         para coluna <- 1 ate 2 faca
         escreva (" Digite um numero da posiçao [",linha,",", coluna,"]:")
         leia ( matri[linha, coluna])
         fimpara
        fimpara

      para linha <- 1 ate 3 faca
         para coluna <- 1 ate 2 faca
         escreva(matri[linha,coluna]:5)
         fimpara
         escreval()
      fimpara

Fimalgoritmo